config/routes.rb
Rails.application.routes.draw do
  resources :bills
  resources :categories
  resources :users, only: [:index] do
    member do
      put :role
    end
  end

  devise_for :users
  root to: 'static_pages#home'

  get '/status' => 'static_pages#status'

  get '/console' => 'static_pages#console'

  require 'sidekiq/web'
  authenticate :user do
    mount Sidekiq::Web => '/sidekiq'
  end

end

app/models/bill.rb
# == Schema Information
#
# Table name: bills
#
#  id          :integer          not null, primary key
#  name        :string           not null
#  category_id :integer
#  price       :float            not null
#  comment     :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  user_id     :integer
#  at          :datetime         default(Thu, 14 May 2015 01:05:20 CST +08:00), not null
#  status      :string           default("paid"), not null
#

class Bill < ActiveRecord::Base

  STATUSES = ['paid', 'abandoned', 'pending']
  include StandardStatus

  belongs_to :category
  belongs_to :user
  has_and_belongs_to_many :users
  has_many :bills_users

  validates :name, presence: true
  validates :price, presence: true
  validates :at, presence: true

  default_value_for :at do
    Time.now
  end

  after_commit :update_category_weight, :update_bills_users

  def update_category_weight
    category.update_weight if category
  end

  def update_bills_users
    bills_users.each do |bu|
      bu.update_attribute :price, price / bills_users.count
    end
  end
end

app/controllers/bills_controller.rb
class BillsController < ApplicationController
  before_action :set_bill, only: [:show, :edit, :update, :destroy]

  # GET /bills
  # GET /bills.json
  def index
    @bills = Bill.order(status: :desc, at: :desc).all
  end

  # GET /bills/1
  # GET /bills/1.json
  def show
  end

  # GET /bills/new
  def new
    @bill = Bill.new
  end

  # GET /bills/1/edit
  def edit
  end

  # POST /bills
  # POST /bills.json
  def create
    @bill = Bill.new(bill_params)

    respond_to do |format|
      if @bill.save
        format.html { redirect_to @bill, notice: 'Bill was successfully created.' }
        format.json { render :show, status: :created, location: @bill }
      else
        format.html { render :new }
        format.json { render json: @bill.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bills/1
  # PATCH/PUT /bills/1.json
  def update
    respond_to do |format|
      if @bill.update(bill_params)
        format.html { redirect_to @bill, notice: 'Bill was successfully updated.' }
        format.json { render :show, status: :ok, location: @bill }
      else
        format.html { render :edit }
        format.json { render json: @bill.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bills/1
  # DELETE /bills/1.json
  def destroy
    @bill.destroy
    respond_to do |format|
      format.html { redirect_to bills_url, notice: 'Bill was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bill
      @bill = Bill.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bill_params
      params.require(:bill).permit(:name, :category_id, :price, :comment, :user_id, :at, :status, user_ids: [])
    end
end

app/views/bills/_form.html.slim
= simple_form_for(@bill) do |f|
  = f.error_notification

  .form-inputs
    = f.input :status, collection: Bill::STATUSES, as: :radio_buttons
    = f.association :category, collection: Category.order(weight: :desc)
    = f.input :name
    = f.input :price
    = f.input :comment
    = f.input :at
    = f.association :user, as: :radio_buttons, label: 'Benefactor'
    = f.association :users, as: :check_boxes, label: 'Beneficiaries'

  .form-actions
    = f.button :submit

app/views/bills/edit.html.slim
h1 Editing bill

== render 'form'

= link_to 'Show', @bill
'|
= link_to 'Back', bills_path

app/views/bills/index.html.slim
h1
  | Listing bills
  |  | 
  = link_to 'New', new_bill_path

table.table
  thead
    tr
      th Status
      th Bill
      th At
      th Category
      th Price
      th Comment
      th Benefactor
      th Beneficiaries

  tbody
    - @bills.each do |bill|
      tr
        td = bill.status
        td = link_for bill
        td = bill.at.to_date
        td = bill.category.name
        td = bill.price
        td = bill.comment
        td = [*bill.user].map(&:name).join(',')
        td = bill.users.map(&:name).join(',')

app/views/bills/new.html.slim
h1 New bill

== render 'form'

= link_to 'Back', bills_path

app/views/bills/show.html.slim
h1
  i = @bill.status
  |  Bill 
  i = @bill.name
  .pull-right
    = link_to 'Back', bills_path
    '  | 
    = link_to 'Edit', edit_bill_path(@bill)
    '  | 
    = link_to 'Destroy', @bill, data: {:confirm => 'Are you sure?'}, :method => :delete

p
  strong Category:
  = link_for @bill.category
p
  strong Price:
  = @bill.price
p
  strong Comment:
  = @bill.comment
p
  strong Benefactor:
  = [*@bill.user].map(&:name).join(',')
p
  strong Beneficiaries:
  = @bill.users.map(&:name).join(',')