config/routes.rb
Rails.application.routes.draw do
  resources :bills
  resources :categories
  resources :users, only: [:index] do
    member do
      put :role
    end
  end

  devise_for :users
  root to: 'static_pages#home'

  get '/status' => 'static_pages#status'

  get '/console' => 'static_pages#console'

  require 'sidekiq/web'
  authenticate :user do
    mount Sidekiq::Web => '/sidekiq'
  end

end

app/models/category.rb
# == Schema Information
#
# Table name: categories
#
#  id         :integer          not null, primary key
#  name       :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  weight     :integer          default(0), not null
#

class Category < ActiveRecord::Base

  has_many :bills

  validates :name, presence: true
  validates :weight, presence: true

  def update_weight
    update_attribute :weight, bills.count
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.order(weight: :desc).all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/views/categories/_form.html.slim
= simple_form_for(@category) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name
    = f.input :weight

  .form-actions
    = f.button :submit

app/views/categories/edit.html.slim
h1 Editing category

== render 'form'

= link_to 'Show', @category
'|
= link_to 'Back', categories_path

app/views/categories/index.html.slim
h1
  | Listing categories
  |  | 
  = link_to 'New', new_category_path

table.table
  thead
    tr
      th Category
      th This Week
      th This month
      th Total

  tbody
    - @categories.each do |category|
      tr
        td = link_for category
        td = category.bills.where(at: Time.now.all_week).sum(:price).round
        td = category.bills.where(at: Time.now.all_month).sum(:price).round
        td = category.bills.sum(:price).round

app/views/categories/new.html.slim
h1 New category

== render 'form'

= link_to 'Back', categories_path

app/views/categories/show.html.slim
h1
  | Category 
  i = @category.name
  .pull-right
    = link_to 'Back', categories_path
    '  | 
    = link_to 'Edit', edit_category_path(@category)
    '  | 
    = link_to 'Destroy', @category, data: {:confirm => 'Are you sure?'}, :method => :delete