config/routes.rb
Rails.application.routes.draw do
  resources :bills
  resources :categories
  resources :users, only: [:index] do
    member do
      put :role
    end
  end

  devise_for :users
  root to: 'static_pages#home'

  get '/status' => 'static_pages#status'

  get '/console' => 'static_pages#console'

  require 'sidekiq/web'
  authenticate :user do
    mount Sidekiq::Web => '/sidekiq'
  end

end

app/views/layouts/_messages.html.slim
/ Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    div class="alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"
      button.close[type="button" data-dismiss="alert" aria-hidden="true"] ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.slim
/ navigation styled for Bootstrap 3.0
nav.navbar.navbar-inverse.navbar-fixed-top
  .container
    .navbar-header
      button.navbar-toggle[type="button" data-toggle="collapse" data-target=".navbar-collapse"]
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      = link_to 'Home', root_path, class: 'navbar-brand'
    .collapse.navbar-collapse
      ul.nav.navbar-nav.pull-right
        == render 'layouts/navigation_links'

app/views/layouts/_navigation_links.html.slim
- if user_signed_in?
  li = link_to 'Categories', categories_path
  li = link_to 'Bills', bills_path
  li = link_to 'Users', users_path
  li = link_to "Sign out", destroy_user_session_path, method: :delete
- else
  li = link_to "Sign in", new_user_session_path
  li = link_to "Sign up", new_user_registration_path

app/views/layouts/application.html.slim
doctype html
html
  head
    meta[name="viewport" content="width=device-width, initial-scale=1.0"]
    title
      = content_for?(:title) ? yield(:title) : 'Period'
    meta name="description" content="#{content_for?(:description) ? yield(:description) : 'Period'}"
    == stylesheet_link_tag "application", :media => 'all', 'data-turbolinks-track' => true
    == javascript_include_tag 'application', 'data-turbolinks-track' => true
    == csrf_meta_tags
  body
    header
      == render 'layouts/navigation'
    main.container[role="main"]
      == render 'layouts/messages'
      == yield